cv_generator/portfolio/urls.py
from django.urls import path

from .views import (
    personal_detail_page,
    project_form_page,
    education_form_page,
    experience_form_page,
    skill_form_page,
    add_section_page,
    home_page,
)

app_name = "portfolio"

urlpatterns = [
    path("basic-info", personal_detail_page, name="basic"),
    path("project-info", project_form_page, name="project"),
    path("education-info", education_form_page, name="education"),
    path("experience-info", experience_form_page, name="experience"),
    path("skill-info", skill_form_page, name="skill"),
    path("custom-edit-info", add_section_page, name="custom_info"),
    # routes of static pages (home_page)
    path(" ", home_page, name="home_page"),
]

cv_generator/website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("portfolio.urls")),
]

cv_generator/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CV Generator </title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"> </script>
    <script src="{% static 'assets/js/style.js' %}"></script>
    <!-- CSS -->
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'assets/c ss/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.mCustomScrollbar.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/media-queries.css' %}">

    <!-- Favicon and touch icons  -->


    <link rel="stylesheet" href="{% static 'assets/ico/favicon.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">




    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>

    <!-- Navigation Bar-->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
        <div class="container-fluid ">
            <a class="navbar-brand" href="#">
                <img src="img/download.jpg">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon ">
                </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item" active>
                        <a class="nav-link fs-4 text-white" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 text-white" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 text-white" href="#">Templates</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 text-white" href="#">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-4 text-white" href="login.html">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Side navbar-->
    <!-- <div class="container-fluid ">
        <div class="row flex-nowrap ">
            <div class="col-auto transparent col-md-3 col-xl-2 px-sm-2 px-0  side-nav" id="side_navbar">
                <div
                    class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100 list-group list-group-flush">
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                        id="menu">
                        <li class="nav-item ">
                            <a class="{% if request.resolver_match.url_name == 'basic' %}current{% endif %}"
                                href="{% url 'portfolio:basic' %}" class="nav-link align-middle px-0">
                                <img rel="icon" type="image/png" src="{% static 'images/profile.png' %}" class="icon">
                                <span class=" ms-3 d-none
                                    d-sm-inline fs-4" id="text">Personal Info</span>
                            </a>
                        </li>
                        <li>
                            <a class="{% if request.resolver_match.url_name == 'skill' %}current{% endif %}"
                                href="{% url 'portfolio:skill' %}" class="nav-link px-0 align-middle">
                                <img rel="icon" type="image/png" src="{% static 'images/skill.png' %}" class="icon">
                                <span class="ms-3 d-none d-sm-inline fs-4 " id="text"> Skills</span></a>
                        </li>
                        <li>
                            <a class="{% if request.resolver_match.url_name == 'project' %}current{% endif %}"
                                href="{% url 'portfolio:project' %}" class="nav-link px-0 align-middle">
                                <img rel="icon" type="image/png" src="{% static 'images/project.png' %}" class="icon">
                                <span class="ms-3 d-none d-sm-inline fs-4 " id="text">Projects</span></a>
                        </li>
                        <li>
                            <a class="{% if request.resolver_match.url_name == 'education' %}current{% endif %}"
                                href="{% url 'portfolio:education' %}" class="nav-link px-0 align-middle">
                                <img rel="icon" type="image/png" src="{% static 'images/education.png' %}" class="icon">
                                <span class="ms-3 d-none d-sm-inline fs-4 " id="text">Education </span></a>
                        </li>
                        <li>
                            <a class="{% if request.resolver_match.url_name == 'experience' %}current{% endif %}"
                                href="{% url 'portfolio:experience' %}" class="nav-link px-0 align-middle">
                                <img rel="icon" type="image/png" src="{% static '/images/work.png' %}" class="icon">

                                <span class="ms-3 d-none d-sm-inline fs-4 " id="text">Experience</span></a>
                        </li>
                        <li>
                            <a class="{% if request.resolver_match.url_name == 'custom_info' %}current{% endif %}"
                                href="{% url 'portfolio:custom_info' %}" class="nav-link px-0 align-middle">
                                <img rel="icon" type="image/png" src="{% static 'images/add.png' %}" class="icon">
                                <span class="ms-3 d-none d-sm-inline fs-4 " id="text">Add Section</span></a>
                        </li>
                    </ul>
                </div> -->
    <!-- Wrapper -->
    <div class="wrapper">

        <!-- Sidebar -->
        <nav class="sidebar">

            <!-- close sidebar menu -->
            <div class="dismiss">
                <i class="fas fa-arrow-left"></i>
            </div>

            <div class="logo">
                <h3><a href="index.html">Bootstrap 4 Template with Sidebar Menu</a></h3>
            </div>

            <ul class="list-unstyled menu-elements">
                <li class="active">
                    <a class="scroll-link" href="#top-content"><i class="fas fa-home"></i> Home</a>
                </li>
                <li>
                    <a class="scroll-link" href="#section-1"><i class="fas fa-cog"></i> What we do</a>
                </li>
                <li>
                    <a class="scroll-link" href="#section-2"><i class="fas fa-user"></i> About us</a>
                </li>
                <li>
                    <a class="scroll-link" href="#section-5"><i class="fas fa-pencil-alt"></i> Portfolio</a>
                </li>
                <li>
                    <a class="scroll-link" href="#section-6"><i class="fas fa-envelope"></i> Contact us</a>
                </li>
                <li>
                    <a href="#otherSections" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"
                        role="button" aria-controls="otherSections">
                        <i class="fas fa-sync"></i>Other sections
                    </a>
                    <ul class="collapse list-unstyled" id="otherSections">
                        <li>
                            <a class="scroll-link" href="#section-3">Our projects</a>
                        </li>
                        <li>
                            <a class="scroll-link" href="#section-4">We think that...</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <div class="to-top">
                <a class="btn btn-primary btn-customized-3" href="#" role="button">
                    <i class="fas fa-arrow-up"></i> Top
                </a>
            </div>

            <div class="dark-light-buttons">
                <a class="btn btn-primary btn-customized-4 btn-customized-dark" href="#" role="button">Dark</a>
                <a class="btn btn-primary btn-customized-4 btn-customized-light" href="#" role="button">Light</a>
            </div>

        </nav>
        <!-- End sidebar -->

        <!-- Dark overlay -->
        <div class="overlay"></div>
    </div>
    <div class="col-10 justify-content-md-center " id="bo">
        <div class="p-5">
            <div class="shadow-lg p-5 mb-4 bg-white rounded ">

                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    </div>
    </div>
</body>